
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CALCULADIN DIVIDE DOIS_PONTOS FINALIZAR ID IGUAL INICIAR INPUT LPAREN MAIS MENOS NUMERO OUTPUT PONTO PONTO_VIRGULA RPAREN VEZESprograma : INICIAR CALCULADIN DOIS_PONTOS lista_comandos FINALIZAR CALCULADIN PONTOprograma : INICIAR error DOIS_PONTOS lista_comandos FINALIZAR CALCULADIN PONTOlista_comandos : lista_comandos comando PONTO_VIRGULA\n                    | emptylista_comandos : lista_comandos error PONTO_VIRGULAcomando : chamada_funcao\n             | atribuicaochamada_funcao : INPUT LPAREN ID RPAREN\n                    | OUTPUT LPAREN ID RPARENatribuicao : ID IGUAL exprexpr : expr MAIS termo\n          | expr MENOS termoexpr : termotermo : termo VEZES fator\n           | termo DIVIDE fatortermo : fatorfator : NUMERO\n           | ID\n           | LPAREN expr RPARENempty :'
    
_lr_action_items = {'INICIAR':([0,],[2,]),'$end':([1,26,35,],[0,-1,-2,]),'CALCULADIN':([2,10,18,],[3,19,25,]),'error':([2,5,6,7,8,9,20,21,],[4,-20,-20,12,-4,12,-3,-5,]),'DOIS_PONTOS':([3,4,],[5,6,]),'FINALIZAR':([5,6,7,8,9,20,21,],[-20,-20,10,-4,18,-3,-5,]),'INPUT':([5,6,7,8,9,20,21,],[-20,-20,15,-4,15,-3,-5,]),'OUTPUT':([5,6,7,8,9,20,21,],[-20,-20,17,-4,17,-3,-5,]),'ID':([5,6,7,8,9,20,21,22,23,24,33,37,38,39,40,],[-20,-20,16,-4,16,-3,-5,27,28,34,28,28,28,28,28,]),'PONTO_VIRGULA':([11,12,13,14,28,29,30,31,32,36,42,43,44,45,46,47,],[20,21,-6,-7,-18,-10,-13,-16,-17,-8,-9,-11,-12,-14,-15,-19,]),'LPAREN':([15,17,23,33,37,38,39,40,],[22,24,33,33,33,33,33,33,]),'IGUAL':([16,],[23,]),'PONTO':([19,25,],[26,35,]),'NUMERO':([23,33,37,38,39,40,],[32,32,32,32,32,32,]),'RPAREN':([27,28,30,31,32,34,41,43,44,45,46,47,],[36,-18,-13,-16,-17,42,47,-11,-12,-14,-15,-19,]),'VEZES':([28,30,31,32,43,44,45,46,47,],[-18,39,-16,-17,39,39,-14,-15,-19,]),'DIVIDE':([28,30,31,32,43,44,45,46,47,],[-18,40,-16,-17,40,40,-14,-15,-19,]),'MAIS':([28,29,30,31,32,41,43,44,45,46,47,],[-18,37,-13,-16,-17,37,-11,-12,-14,-15,-19,]),'MENOS':([28,29,30,31,32,41,43,44,45,46,47,],[-18,38,-13,-16,-17,38,-11,-12,-14,-15,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'lista_comandos':([5,6,],[7,9,]),'empty':([5,6,],[8,8,]),'comando':([7,9,],[11,11,]),'chamada_funcao':([7,9,],[13,13,]),'atribuicao':([7,9,],[14,14,]),'expr':([23,33,],[29,41,]),'termo':([23,33,37,38,],[30,30,43,44,]),'fator':([23,33,37,38,39,40,],[31,31,31,31,45,46,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> INICIAR CALCULADIN DOIS_PONTOS lista_comandos FINALIZAR CALCULADIN PONTO','programa',7,'p_programa','parser.py',20),
  ('programa -> INICIAR error DOIS_PONTOS lista_comandos FINALIZAR CALCULADIN PONTO','programa',7,'p_programa_erro','parser.py',23),
  ('lista_comandos -> lista_comandos comando PONTO_VIRGULA','lista_comandos',3,'p_lista_comandos','parser.py',29),
  ('lista_comandos -> empty','lista_comandos',1,'p_lista_comandos','parser.py',30),
  ('lista_comandos -> lista_comandos error PONTO_VIRGULA','lista_comandos',3,'p_lista_comandos_erro','parser.py',33),
  ('comando -> chamada_funcao','comando',1,'p_comando','parser.py',39),
  ('comando -> atribuicao','comando',1,'p_comando','parser.py',40),
  ('chamada_funcao -> INPUT LPAREN ID RPAREN','chamada_funcao',4,'p_chamada_funcao','parser.py',45),
  ('chamada_funcao -> OUTPUT LPAREN ID RPAREN','chamada_funcao',4,'p_chamada_funcao','parser.py',46),
  ('atribuicao -> ID IGUAL expr','atribuicao',3,'p_atribuicao','parser.py',61),
  ('expr -> expr MAIS termo','expr',3,'p_expr','parser.py',70),
  ('expr -> expr MENOS termo','expr',3,'p_expr','parser.py',71),
  ('expr -> termo','expr',1,'p_expr_termo','parser.py',76),
  ('termo -> termo VEZES fator','termo',3,'p_termo','parser.py',81),
  ('termo -> termo DIVIDE fator','termo',3,'p_termo','parser.py',82),
  ('termo -> fator','termo',1,'p_termo_fator','parser.py',87),
  ('fator -> NUMERO','fator',1,'p_fator','parser.py',92),
  ('fator -> ID','fator',1,'p_fator','parser.py',93),
  ('fator -> LPAREN expr RPAREN','fator',3,'p_fator','parser.py',94),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',103),
]
